L4Re Reference Manual
L4Re - L4 Runtime Environment
L4::Kip::Mem_desc Class Reference
[Kernel Interface Page]
Memory descriptors stored in the kernel interface page.
Public Types
enum Mem_type
Memory types.
Public Member Functions
Mem_desc (unsigned long start, unsigned long end, Mem_type t, unsigned char st=0, bool virt=false) throw ()
Initialize memory descriptor.
unsigned long start () const throw ()
Return start address of memory descriptor.
unsigned long end () const throw ()
Return end address of memory descriptor.
unsigned long size () const throw ()
Return size of region described by the memory descriptor.
Mem_type type () const throw ()
Return type of the memory descriptor.
unsigned char sub_type () const throw ()
Return sub-type of the memory descriptor.
unsigned is_virtual () const throw ()
Return whether the memory descriptor describes a virtual or physical region.
void set (unsigned long start, unsigned long end, Mem_type t, unsigned char st=0, bool virt=false) throw ()
Set values of a memory descriptor.
Static Public Member Functions
static Mem_desc * first (void *kip) throw ()
Get first memory descriptor.
static unsigned long count (void const *kip) throw ()
Return number of memory descriptors stored in the kernel info page.
static void count (void *kip, unsigned count) throw ()
Set number of memory descriptors.
Detailed Description
Memory descriptors stored in the kernel interface page.
#include <l4/sys/kip>
Definition at line 51 of file kip.
Constructor & Destructor Documentation
L4::Kip::Mem_desc::Mem_desc (unsigned long start, unsigned long end, Mem_type t, unsigned char st = 0, bool virt = false) throw () [inline]
Initialize memory descriptor.
Parameters:
start Start address
end End address
t Memory type
st Memory subtype, defaults to 0
virt True for virtual memory, false for physical memory, defaults to physical
Definition at line 125 of file kip.
Member Function Documentation
static Mem_desc* L4::Kip::Mem_desc::first (void * kip) throw () [inline, static]
Get first memory descriptor.
Parameters:
kip Pointer to the kernel info page
Returns:
First memory descriptor stored in the kernel info page
Definition at line 83 of file kip.
static unsigned long L4::Kip::Mem_desc::count (void const * kip) throw () [inline, static]
Return number of memory descriptors stored in the kernel info page.
Parameters:
kip Pointer to the kernel info page
Returns:
Number of memory descriptors in the kernel info page.
Definition at line 100 of file kip.
static void L4::Kip::Mem_desc::count (void * kip, unsigned count) throw () [inline, static]
Set number of memory descriptors.
Parameters:
kip Pointer to the kernel info page
count Number of memory descriptors
Definition at line 110 of file kip.
unsigned long L4::Kip::Mem_desc::start () const throw () [inline]
Return start address of memory descriptor.
Returns:
Start address of memory descriptor
Definition at line 135 of file kip.
Referenced by set(), and size().
unsigned long L4::Kip::Mem_desc::end () const throw () [inline]
Return end address of memory descriptor.
Returns:
End address of memory descriptor
Definition at line 141 of file kip.
Referenced by set(), and size().
unsigned long L4::Kip::Mem_desc::size () const throw () [inline]
Return size of region described by the memory descriptor.
Returns:
Size of the region described by the memory descriptor
Definition at line 147 of file kip.
References end(), and start().
Mem_type L4::Kip::Mem_desc::type () const throw () [inline]
Return type of the memory descriptor.
Returns:
Type of the memory descriptor
Definition at line 153 of file kip.
unsigned char L4::Kip::Mem_desc::sub_type () const throw () [inline]
Return sub-type of the memory descriptor.
Returns:
Sub-type of the memory descriptor
Definition at line 159 of file kip.
unsigned L4::Kip::Mem_desc::is_virtual () const throw () [inline]
Return whether the memory descriptor describes a virtual or physical region.
Returns:
True for virtual region, false for physical region.
Definition at line 166 of file kip.
void L4::Kip::Mem_desc::set (unsigned long start, unsigned long end, Mem_type t, unsigned char st = 0, bool virt = false) throw () [inline]
Set values of a memory descriptor.
Parameters:
start Start address
end End address
t Memory type
st Sub-type, defaults to 0
virt Virtual or physical memory region, defaults to physical
Definition at line 176 of file kip.
References end(), and start().
The documentation for this class was generated from the following file:
l4/sys/kip
L4Re - L4 Runtime Environment