L4Re Reference Manual
L4Re - L4 Runtime Environment
cxx::List_item Class Reference
[Small C++ Template Lib]
Basic list item.
Inherited by cxx::Base_slab< Obj_size, Slab_size, Max_free, Alloc >::Slab_head, and cxx::List< D, Alloc >::E.
Data Structures
class Iter
Iterator for a list of ListItem-s.
class T_iter
Iterator for derived classes from ListItem.
Public Member Functions
List_item * get_prev_item () const throw ()
Get previous item.
List_item * get_next_item () const throw ()
Get next item.
void insert_prev_item (List_item *p) throw ()
Insert item p before this item.
void insert_next_item (List_item *p) throw ()
Insert item p after this item.
void remove_me () throw ()
Remove this item from the list.
Static Public Member Functions
template<typename C , typename N >
static C * push_back (C *head, N *p) throw ()
Append item to a list.
template<typename C , typename N >
static C * push_front (C *head, N *p) throw ()
Prepend item to a list.
template<typename C , typename N >
static C * remove (C *head, N *p) throw ()
Remove item from a list.
Detailed Description
Basic list item.
Basic item that can be member of a doubly linked, cyclic list.
Definition at line 37 of file list.
Member Function Documentation
List_item* cxx::List_item::get_prev_item () const throw () [inline]
Get previous item.
Definition at line 174 of file list.
List_item* cxx::List_item::get_next_item () const throw () [inline]
Get next item.
Definition at line 177 of file list.
void cxx::List_item::insert_prev_item (List_item * p) throw () [inline]
Insert item p before this item.
Definition at line 180 of file list.
void cxx::List_item::insert_next_item (List_item * p) throw () [inline]
Insert item p after this item.
Definition at line 190 of file list.
void cxx::List_item::remove_me () throw () [inline]
Remove this item from the list.
Definition at line 199 of file list.
Referenced by cxx::List_item::Iter::remove_me().
template<typename C , typename N > C * cxx::List_item::push_back (C * head, N * p) throw () [inline, static]
Append item to a list.
Convinience function for empty-head corner case.
Parameters:
h pointer to the current list head.
p pointer to new item.
Returns:
the pointer to the new head.
Definition at line 249 of file list.
Referenced by cxx::List< D, Alloc >::push_back().
template<typename C , typename N > C * cxx::List_item::push_front (C * head, N * p) throw () [inline, static]
Prepend item to a list.
Convinience function for empty-head corner case.
Parameters:
head pointer to the current list head.
p pointer to new item.
Returns:
the pointer to the new head.
Definition at line 260 of file list.
Referenced by cxx::List< D, Alloc >::push_front().
template<typename C , typename N > C * cxx::List_item::remove (C * head, N * p) throw () [inline, static]
Remove item from a list.
Convinience function for remove-head corner case.
Parameters:
head pointer to the current list head.
p pointer to the item to remove.
Returns:
the pointer to the new head.
Definition at line 270 of file list.
Referenced by cxx::List< D, Alloc >::remove().
The documentation for this class was generated from the following file:
l4/cxx/list
L4Re - L4 Runtime Environment