L4Re Reference Manual
L4Re - L4 Runtime Environment
L4Re::Util::Event_buffer_consumer_t< PAYLOAD > Class Template Reference
[L4Re Util C++ Interface]
An event buffer consumer.
Public Member Functions
template<typename CB , typename D >
void foreach_available_event (CB const &cb, D data=D())
Call function on every available event.
template<typename CB , typename D >
void process (L4::Cap< L4::Irq > irq, L4::Cap< L4::Thread > thread, CB const &cb, D data=D())
Continuously wait for events and process them.
Detailed Description
template<typename PAYLOAD>
class L4Re::Util::Event_buffer_consumer_t< PAYLOAD >
An event buffer consumer.
Definition at line 90 of file event_buffer.
Member Function Documentation
template<typename PAYLOAD > template<typename CB , typename D > void L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::foreach_available_event (CB const & cb, D data = D()) [inline]
Call function on every available event.
Parameters:
cb Function callback.
Definition at line 100 of file event_buffer.
References L4Re::Event_buffer_t< PAYLOAD >::Event::free().
Referenced by L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::process().
template<typename PAYLOAD > template<typename CB , typename D > void L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::process (L4::Cap< L4::Irq > irq, L4::Cap< L4::Thread > thread, CB const & cb, D data = D()) [inline]
Continuously wait for events and process them.
Parameters:
irq Event signal to wait for.
thread Thread capability of the thread calling this function.
cb Callback function that is called for each received event.
Note:
This function never returns.
Definition at line 120 of file event_buffer.
References L4::Cap_base::cap(), L4Re::Util::Event_buffer_consumer_t< PAYLOAD >::foreach_available_event(), l4_error(), l4_ipc_error(), l4_irq_receive(), and l4_utcb().
The documentation for this class was generated from the following file:
l4/re/util/event_buffer
L4Re - L4 Runtime Environment