L4Re Reference Manual
L4Re - L4 Runtime Environment
cxx::Avl_tree< Node, Get_key, Compare > Class Template Reference
A generic AVL tree.
Public Types
typedef Bst::Key_type Key_type
The type of key values used to generate the total order of the elements.
typedef Bst::Key_param_type Key_param_type
The type for key parameters.
typedef Bst::Iterator Iterator
Grab iterator types from Bst.
typedef Bst::Const_iterator Const_iterator
Constant forward iterator for the set.
typedef Bst::Rev_iterator Rev_iterator
Backward iterator for the set.
typedef Bst::Const_rev_iterator Const_rev_iterator
Constant backward iterator for the set.
Public Member Functions
Pair< Node *, bool > insert (Node *new_node)
Insert a new node into this AVL tree.
Node * remove (Key_param_type key)
Remove the node with key from the tree.
Node * erase (Key_param_type key)
An alias for remove().
Avl_tree ()
Create an empty AVL tree.
~Avl_tree ()
Destroy, and free the set.
Detailed Description
template<typename Node, typename Get_key, typename Compare = Lt_functor<typename Get_key::Key_type>>
class cxx::Avl_tree< Node, Get_key, Compare >
A generic AVL tree.
Parameters:
Node the data type of the nodes (must inherit from Avl_tree_noed).
Get_key the meta fcuntion to get the key value from a node. The implementation uses Get_key::key_of(ptr_to_node).
Compare binary relation to establish a total order for the nodes of the tree. Compare()(l, r) must return true if the key l is smaller than the key r.
Examples:
tmpfs/lib/src/fs.cc.
Definition at line 102 of file avl_tree.
Member Typedef Documentation
template<typename Node, typename Get_key, typename Compare = Lt_functor<typename Get_key::Key_type>> typedef Bst::Iterator cxx::Avl_tree< Node, Get_key, Compare >::Iterator
Grab iterator types from Bst.
Forward iterator for the set.
Reimplemented from cxx::Bits::Bst< Node, Get_key, Compare >.
Definition at line 133 of file avl_tree.
Member Function Documentation
template<typename Node, typename Get_key , class Compare > Pair< Node *, bool > cxx::Avl_tree< Node, Get_key, Compare >::insert (Node * new_node)
Insert a new node into this AVL tree.
Parameters:
new_node a pointer to the new node. This node must not already b in an AVL tree.
Returns:
A pair, with second set to 'true' and first pointing to new_node, on success. If there is already a node with the same key that first point to this node and second is 'false'.
Definition at line 225 of file avl_tree.
References cxx::Bits::Bst< Node, Get_key, Compare >::_head, cxx::Bits::Bst< Node, Get_key, Compare >::dir(), cxx::Bits::Bst< Node, Get_key, Compare >::greater(), and cxx::Bits::Direction::N.
template<typename Node , typename Get_key , class Compare > Node * cxx::Avl_tree< Node, Get_key, Compare >::remove (Key_param_type key) [inline]
Remove the node with key from the tree.
Parameters:
key The node to remove.
Returns:
The pointer to the removed node on success, or NULL -3 if no node with the key exists.
Definition at line 287 of file avl_tree.
References cxx::Bits::Bst< Node, Get_key, Compare >::_head, cxx::Bits::Bst< Node, Get_key, Compare >::greater(), cxx::Bits::Bst< Node, Get_key, Compare >::k(), cxx::Bits::Direction::L, and cxx::Bits::Direction::N.
Referenced by cxx::Avl_set< Pair< Region, Hdlr >, Pair_first_compare< cxx::Lt_functor< Region >, Pair< Region, Hdlr > >, Alloc >::remove().
The documentation for this class was generated from the following file:
l4/cxx/avl_tree
L4Re - L4 Runtime Environment