L4Re Reference Manual
L4Re - L4 Runtime Environment
L4Re::Cap_alloc Class Reference
[L4Re Capability API]
Capability allocator interface.
Public Member Functions
virtual L4::Cap< void > alloc ()=0 throw ()
Allocate a capability.
template<typename T >
L4::Cap< T > alloc () throw ()
Allocate a capability.
virtual void free (L4::Cap< void > cap)=0 throw ()
Free a capability.
virtual ~Cap_alloc ()=0
Destructor.
Static Public Member Functions
template<typename CAP_ALLOC >
static L4Re::Cap_alloc * get_cap_alloc (CAP_ALLOC &ca)
Construct an instance of a capability allocator.
Detailed Description
Capability allocator interface.
Definition at line 39 of file cap_alloc.
Member Function Documentation
virtual L4::Cap<void> L4Re::Cap_alloc::alloc () throw () [pure virtual]
Allocate a capability.
Returns:
Capability of type void
Referenced by alloc(), and get_cap_alloc().
template<typename T > L4::Cap<T> L4Re::Cap_alloc::alloc () throw () [inline]
Allocate a capability.
Returns:
Capability of type T
Definition at line 61 of file cap_alloc.
References alloc(), and L4::cap_cast().
virtual void L4Re::Cap_alloc::free (L4::Cap< void > cap) throw () [pure virtual]
Free a capability.
Parameters:
cap Capability to free.
Referenced by get_cap_alloc().
template<typename CAP_ALLOC > static L4Re::Cap_alloc* L4Re::Cap_alloc::get_cap_alloc (CAP_ALLOC & ca) [inline, static]
Construct an instance of a capability allocator.
Parameters:
ca Capaiblity allocator
Returns:
Instance of a capability allocator.
Definition at line 84 of file cap_alloc.
References alloc(), and free().
The documentation for this class was generated from the following file:
l4/re/cap_alloc
L4Re - L4 Runtime Environment