L4Re Reference Manual
L4Re - L4 Runtime Environment
L4::Ipc::Iostream Class Reference
Input/Output stream for IPC [un]marshalling.
Public Member Functions
Iostream (l4_utcb_t *utcb)
Create an IPC IO stream with a single message buffer.
void reset ()
Reset the stream to its initial state.
IPC operations.
l4_msgtag_t call (l4_cap_idx_t dst)
Do an IPC call using the message in the output stream and receiving to the input stream.
l4_msgtag_t call (l4_cap_idx_t dst, long label)
l4_msgtag_t reply_and_wait (l4_umword_t *src_dst, long proto=0)
Do an IPC reply and wait.
l4_msgtag_t send_and_wait (l4_cap_idx_t dest, l4_umword_t *src, long proto=0)
l4_msgtag_t reply_and_wait (l4_umword_t *src_dst, l4_timeout_t timeout, long proto=0)
Do an IPC reply and wait.
l4_msgtag_t send_and_wait (l4_cap_idx_t dest, l4_umword_t *src, l4_timeout_t timeout, long proto=0)
l4_msgtag_t reply (l4_timeout_t timeout, long proto=0)
l4_msgtag_t reply (long proto=0)
Detailed Description
Input/Output stream for IPC [un]marshalling.
The Ipc::Iostream is part of the AW Env IPC framework as well as Ipc::Istream and Ipc::Ostream. In particular an Ipc::Iostream is a combination of an Ipc::Istream and an Ipc::Ostream. It can use either a single message buffer for receiving and sending messages or a pair of a receive and a send buffer. The stream also supports combined IPC operations such as call() and reply_and_wait(), which can be used to implement RPC functionality.
Examples:
examples/clntsrv/client.cc, examples/clntsrv/server.cc, examples/libs/l4re/c++/shared_ds/ds_srv.cc, examples/libs/l4re/streammap/client.cc, and examples/libs/l4re/streammap/server.cc.
Definition at line 995 of file ipc_stream.
Constructor & Destructor Documentation
L4::Ipc::Iostream::Iostream (l4_utcb_t * utcb) [inline, explicit]
Create an IPC IO stream with a single message buffer.
Parameters:
msg The message buffer used as backing store.
The created IO stream uses the same message buffer for sending and receiving IPC messages.
Definition at line 1006 of file ipc_stream.
Member Function Documentation
void L4::Ipc::Iostream::reset () [inline]
Reset the stream to its initial state.
Input as well as the output stream are reset.
Reimplemented from L4::Ipc::Ostream.
Definition at line 1016 of file ipc_stream.
l4_msgtag_t L4::Ipc::Iostream::call (l4_cap_idx_t dst) [inline]
Do an IPC call using the message in the output stream and receiving to the input stream.
Parameters:
dst The destination L4 UID (thread) to call.
Returns:
the result dope of the IPC operation.
This is a combined IPC operation consisting of a send and a receive to/from the given destination dst.
A call is usually used by clients for RPCs to a server.
Examples:
examples/clntsrv/client.cc, and examples/libs/l4re/streammap/client.cc.
Definition at line 1154 of file ipc_stream.
References l4_ipc_call(), L4_IPC_NEVER, and L4::Ipc::Istream::tag().
Referenced by L4Re::Dataspace::allocate(), L4Re::Dataspace::info(), and L4Re::Dataspace::phys().
l4_msgtag_t L4::Ipc::Iostream::reply_and_wait (l4_umword_t * src_dst, long proto = 0) [inline]
Do an IPC reply and wait.
Parameters:
src_dst Input: the destination for the send operation.
Output: the source of the received message.
Returns:
the result dope of the IPC operation.
This is a combined IPC operation consisting of a send operation and an open wait for any message.
A reply and wait is usually used by servers that reply to a client and wait for the next request by any other client.
Definition at line 1071 of file ipc_stream.
References L4_IPC_SEND_TIMEOUT_0, and reply_and_wait().
Referenced by reply_and_wait().
l4_msgtag_t L4::Ipc::Iostream::reply_and_wait (l4_umword_t * src_dst, l4_timeout_t timeout, long proto = 0) [inline]
Do an IPC reply and wait.
Parameters:
src_dst Input: the destination for the send operation.
Output: the source of the received message.
timeout Timeout used for IPC.
Returns:
the result dope of the IPC operation.
This is a combined IPC operation consisting of a send operation and an open wait for any message.
A reply and wait is usually used by servers that reply to a client and wait for the next request by any other client.
Definition at line 1175 of file ipc_stream.
References l4_ipc_reply_and_wait(), and L4::Ipc::Istream::tag().
The documentation for this class was generated from the following file:
l4/cxx/ipc_stream
L4Re - L4 Runtime Environment