L4Re Reference Manual
L4Re - L4 Runtime Environment
Interrupt controller
[Kernel Objects]
The ICU class.
Data Structures
struct l4_icu_info_t
Info structure for an ICU.
class L4::Icu
C++ version of an interrupt controller.
class L4::Icu::Info
Info for an ICU.
Typedefs
typedef struct l4_icu_info_t l4_icu_info_t
Info structure for an ICU.
Enumerations
enum L4_icu_flags { L4_ICU_FLAG_MSI }
Flags for IRQ numbers used for the ICU.
Functions
l4_msgtag_t l4_icu_bind (l4_cap_idx_t icu, unsigned irqnum, l4_cap_idx_t irq) throw ()
Bind an interrupt vector of an interrupt controller to an interrupt object.
l4_msgtag_t l4_icu_unbind (l4_cap_idx_t icu, unsigned irqnum, l4_cap_idx_t irq) throw ()
Remove binding of an interrupt vector from the interrupt controller object.
l4_msgtag_t l4_icu_set_mode (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t mode) throw ()
Set mode of interrupt.
l4_msgtag_t l4_icu_info (l4_cap_idx_t icu, l4_icu_info_t *info) throw ()
Get info about capabilites of ICU.
l4_msgtag_t l4_icu_msi_info (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t *msg) throw ()
Get MSI info about IRQ.
l4_msgtag_t l4_icu_unmask (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t *label, l4_timeout_t to) throw ()
Unmask an IRQ vector.
l4_msgtag_t l4_icu_mask (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t *label, l4_timeout_t to) throw ()
Mask an IRQ vector.
Detailed Description
The ICU class.
#include <l4/sys/icu.h>
Typedef Documentation
typedef struct l4_icu_info_t l4_icu_info_t
Info structure for an ICU.
This structure contains information about the features of an ICU.
See also:
l4_icu_info().
Enumeration Type Documentation
enum L4_icu_flags
Flags for IRQ numbers used for the ICU.
Enumerator:
L4_ICU_FLAG_MSI
Flag to denote that the IRQ is actually an MSI.
This flag may be used for l4_icu_bind() and l4_icu_unbind() functions to denote that the IRQ number is meant to be an MSI.
Definition at line 44 of file icu.h.
Function Documentation
l4_msgtag_t l4_icu_bind (l4_cap_idx_t icu, unsigned irqnum, l4_cap_idx_t irq) throw () [inline]
Bind an interrupt vector of an interrupt controller to an interrupt object.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
irq IRQ capability to bind the IRQ to.
Returns:
Syscall return tag
Examples:
examples/sys/isr/main.c.
Definition at line 398 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_unbind (l4_cap_idx_t icu, unsigned irqnum, l4_cap_idx_t irq) throw () [inline]
Remove binding of an interrupt vector from the interrupt controller object.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
irq IRQ object to remove from the ICU.
Returns:
Syscall return tag
Definition at line 402 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_set_mode (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t mode) throw () [inline]
Set mode of interrupt.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
mode Mode, see L4_irq_flow_type.
Returns:
Syscall return tag
Definition at line 424 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_info (l4_cap_idx_t icu, l4_icu_info_t * info) throw () [inline]
Get info about capabilites of ICU.
Parameters:
icu ICU to use.
info Pointer to an info structure to be filled with information.
Returns:
Syscall return tag
Definition at line 406 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_msi_info (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t * msg) throw () [inline]
Get MSI info about IRQ.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
msg Pointer to a word to receive the message that must be used for the PCI devices MSI message.
Returns:
Syscall return tag
Definition at line 410 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_unmask (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t * label, l4_timeout_t to) throw () [inline]
Unmask an IRQ vector.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
label If non-NULL the function also waits for the next message.
to Timeout for message to ICU, if unsure use L4_IPC_NEVER.
Returns:
Syscall return tag
Definition at line 414 of file icu.h.
References l4_utcb().
l4_msgtag_t l4_icu_mask (l4_cap_idx_t icu, unsigned irqnum, l4_umword_t * label, l4_timeout_t to) throw () [inline]
Mask an IRQ vector.
Parameters:
icu ICU to use.
irqnum IRQ vector at the ICU.
label If non-NULL the function also waits for the next message.
to Timeout for message to ICU, if unsure use L4_IPC_NEVER.
Returns:
Syscall return tag
Definition at line 419 of file icu.h.
References l4_utcb().
L4Re - L4 Runtime Environment