L4Re Reference Manual
L4Re - L4 Runtime Environment
Fiasco extensions
[Base API]
Kernel debugger extensions of the Fiasco L4 implementation.
Data Structures
struct l4_tracebuffer_status_t
Trace buffer status.
struct l4_tracebuffer_status_window_t
Trace-buffer status window descriptor.
Modules
Fiasco real time scheduling extensions
Real time scheduling extension for the Fiasco L4 implementation.
Kernel Debugger
Kernel debugger related functionality.
Files
file segment.h
l4f specific segment manipulation
Defines
#define LOG_EVENT_CONTEXT_SWITCH 0
Event: context switch.
#define LOG_EVENT_IPC_SHORTCUT 1
Event: IPC shortcut.
#define LOG_EVENT_IRQ_RAISED 2
Event: IRQ occurred.
#define LOG_EVENT_TIMER_IRQ 3
Event: Timer IRQ occurred.
#define LOG_EVENT_THREAD_EX_REGS 4
Event: thread_ex_regs.
#define LOG_EVENT_MAX_EVENTS 16
Maximum number of events.
#define LOG_EVENT_CONTEXT_SWITCH 0
Event: context switch.
#define LOG_EVENT_IPC_SHORTCUT 1
Event: IPC shortcut.
#define LOG_EVENT_IRQ_RAISED 2
Event: IRQ occurred.
#define LOG_EVENT_TIMER_IRQ 3
Event: Timer IRQ occurred.
#define LOG_EVENT_THREAD_EX_REGS 4
Event: thread_ex_regs.
#define LOG_EVENT_MAX_EVENTS 16
Maximum number of events.
Enumerations
enum
Log event types.
Functions
l4_tracebuffer_status_t * fiasco_tbuf_get_status (void)
Return trace buffer status.
l4_addr_t fiasco_tbuf_get_status_phys (void)
Return the physical address of the trace buffer status struct.
l4_umword_t fiasco_tbuf_log (const char *text)
Create new trace buffer entry with describing <text>.
l4_umword_t fiasco_tbuf_log_3val (const char *text, unsigned v1, unsigned v2, unsigned v3)
Create new trace buffer entry with describing <text> and three additional values.
l4_umword_t fiasco_tbuf_log_binary (const unsigned char *data)
Create new trace buffer entry with binary data.
void fiasco_tbuf_clear (void)
Clear trace buffer.
void fiasco_tbuf_dump (void)
Dump trace buffer to kernel console.
void fiasco_profile_start (void) throw ()
Start profiling.
void fiasco_profile_stop_and_dump (void) throw ()
Stop profiling and dump result to console.
void fiasco_profile_stop (void) throw ()
Stop profiling.
void fiasco_watchdog_enable (void) throw ()
Enable Fiasco watchdog.
void fiasco_watchdog_disable (void) throw ()
Disable Fiasco watchdog.
void fiasco_watchdog_takeover (void) throw ()
Disable automatic resetting of watchdog.
void fiasco_watchdog_giveback (void) throw ()
Reenable automatic resetting of watchdog.
void fiasco_watchdog_touch (void) throw ()
Reset watchdog from user land.
long fiasco_ldt_set (l4_cap_idx_t task, void *ldt, unsigned int size, unsigned int entry_number_start, l4_utcb_t *utcb)
Set LDT segments descriptors.
long fiasco_gdt_set (l4_cap_idx_t thread, void *desc, unsigned int size, unsigned int entry_number_start, l4_utcb_t *utcb)
Set GDT segment descriptors.
unsigned fiasco_gdt_get_entry_offset (l4_cap_idx_t thread, l4_utcb_t *utcb)
Return the offset of the entry in the GDT.
Detailed Description
Kernel debugger extensions of the Fiasco L4 implementation.
Function Documentation
l4_tracebuffer_status_t * fiasco_tbuf_get_status (void) [inline]
Return trace buffer status.
Return trace-buffer status.
Return tracebuffer status.
Returns:
Pointer to trace buffer status struct.
Pointer to tracebuffer status struct.
Pointer to trace-buffer status struct.
Definition at line 171 of file ktrace.h.
l4_addr_t fiasco_tbuf_get_status_phys (void) [inline]
Return the physical address of the trace buffer status struct.
Return the physical address of the trace-buffer status struct.
Return the physical address of the tracebuffer status struct.
Returns:
physical address of status struct.
Definition at line 178 of file ktrace.h.
References enter_kdebug.
l4_umword_t fiasco_tbuf_log (const char * text) [inline]
Create new trace buffer entry with describing <text>.
Create new trace-buffer entry with describing <text>.
Create new tracebuffer entry with describing <text>.
Parameters:
text Logging text
Returns:
Pointer to trace buffer entry
Parameters:
text Logging text
Returns:
Pointer to tracebuffer entry
Parameters:
text Logging text
Returns:
Pointer to trace-buffer entry
Definition at line 185 of file ktrace.h.
l4_umword_t fiasco_tbuf_log_3val (const char * text, unsigned v1, unsigned v2, unsigned v3) [inline]
Create new trace buffer entry with describing <text> and three additional values.
Create new trace-buffer entry with describing <text> and three additional values.
Create new tracebuffer entry with describing <text> and three additional values.
Parameters:
text Logging text
v1 first value
v2 second value
v3 third value
Returns:
Pointer to trace buffer entry
Parameters:
text Logging text
v1 first value
v2 second value
v3 third value
Returns:
Pointer to tracebuffer entry
Parameters:
text Logging text
v1 first value
v2 second value
v3 third value
Returns:
Pointer to trace-buffer entry
Definition at line 191 of file ktrace.h.
l4_umword_t fiasco_tbuf_log_binary (const unsigned char * data) [inline]
Create new trace buffer entry with binary data.
Create new trace-buffer entry with binary data.
Create new tracebuffer entry with binary data.
Parameters:
data binary data
Returns:
Pointer to trace buffer entry
Parameters:
data binary data
Returns:
Pointer to tracebuffer entry
Parameters:
data binary data
Returns:
Pointer to trace-buffer entry
Definition at line 221 of file ktrace.h.
void fiasco_tbuf_clear (void) [inline]
Clear trace buffer.
Clear trace-buffer.
Clear tracebuffer.
Definition at line 197 of file ktrace.h.
void fiasco_tbuf_dump (void) [inline]
Dump trace buffer to kernel console.
Dump trace-buffer to kernel console.
Dump tracebuffer to kernel console.
Definition at line 203 of file ktrace.h.
void fiasco_watchdog_takeover (void) throw () [inline]
Disable automatic resetting of watchdog.
User is responsible to call fiasco_watchdog_touch from time to time to ensure that the watchdog does not trigger.
Definition at line 407 of file kdebug.h.
void fiasco_watchdog_touch (void) throw () [inline]
Reset watchdog from user land.
This function must be called from time to time to prevent the watchdog from triggering if the watchdog is activated and if fiasco_watchdog_takeover was performed.
Definition at line 419 of file kdebug.h.
long fiasco_ldt_set (l4_cap_idx_t task, void * ldt, unsigned int size, unsigned int entry_number_start, l4_utcb_t * utcb) [inline]
Set LDT segments descriptors.
Parameters:
task Task to set the segment for.
ldt Pointer to LDT hardware descriptors.
num_desc Number of descriptors.
entry_number_start Entry number to start.
utcb UTCB of the caller.
Definition at line 94 of file segment.h.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), L4_PROTO_TASK, and l4_msg_regs_t::mr.
long fiasco_gdt_set (l4_cap_idx_t thread, void * desc, unsigned int size, unsigned int entry_number_start, l4_utcb_t * utcb) [inline]
Set GDT segment descriptors.
Fiasco supports 3 consecutive entries, starting at the value returned by fiasco_gdt_get_entry_offset()
Parameters:
thread Thread to set the GDT entry for.
desc Pointer to GDT descriptors.
size Size of the descriptors in bytes (multiple of 8).
entry_number_start Entry number to start (valid values: 0-2).
utcb UTCB of the caller.
Returns:
System call error
Definition at line 35 of file segment.h.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), L4_PROTO_THREAD, and l4_msg_regs_t::mr.
unsigned fiasco_gdt_get_entry_offset (l4_cap_idx_t thread, l4_utcb_t * utcb) [inline]
Return the offset of the entry in the GDT.
Parameters:
thread Thread to get info from.
utcb UTCB of the caller.
Definition at line 107 of file segment.h.
References l4_ipc_call(), L4_IPC_NEVER, l4_msgtag(), L4_PROTO_THREAD, and l4_msg_regs_t::mr.
L4Re - L4 Runtime Environment