L4Re Reference Manual
L4Re - L4 Runtime Environment
vCPU Support Library
vCPU handling functionality.
Data Structures
class L4vcpu::State
C++ implementation of state word in the vCPU area.
class L4vcpu::Vcpu
C++ implementation of the vCPU save state area.
Modules
Extended vCPU support
extended vCPU handling functionality.
Typedefs
typedef enum l4vcpu_irq_state_t l4vcpu_irq_state_t
IRQ/Event enable and disable flags.
Enumerations
enum l4vcpu_irq_state_t { L4VCPU_IRQ_STATE_DISABLED = 0, L4VCPU_IRQ_STATE_ENABLED = L4_VCPU_F_IRQ }
IRQ/Event enable and disable flags.
Functions
l4vcpu_state_t l4vcpu_state (l4_vcpu_state_t const *vcpu) throw ()
Return the state flags of a vCPU.
void l4vcpu_irq_disable (l4_vcpu_state_t *vcpu) throw ()
Disable a vCPU for event delivery.
l4vcpu_irq_state_t l4vcpu_irq_disable_save (l4_vcpu_state_t *vcpu) throw ()
Disable a vCPU for event delivery and return previous state.
void l4vcpu_irq_enable (l4_vcpu_state_t *vcpu, l4_utcb_t *utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw ()
Enable a vCPU for event delivery.
void l4vcpu_irq_restore (l4_vcpu_state_t *vcpu, l4vcpu_irq_state_t s, l4_utcb_t *utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw ()
Restore a previously saved IRQ/event state.
void l4vcpu_halt (l4_vcpu_state_t *vcpu, l4_utcb_t *utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw ()
Halt the vCPU (sleep).
void l4vcpu_print_state (l4_vcpu_state_t *vcpu, const char *prefix) throw ()
Print the state of a vCPU.
int l4vcpu_is_irq_entry (l4_vcpu_state_t *vcpu) throw ()
Return whether the entry reason was an IRQ/IPC message.
int l4vcpu_is_page_fault_entry (l4_vcpu_state_t *vcpu) throw ()
Return whether the entry reason was a page fault.
Detailed Description
vCPU handling functionality.
This library provides convenience functionality on top of the l4sys vCPU interface to ease programming. It wraps commonly used code and abstracts architecture depends parts as far as reasonable.
Enumeration Type Documentation
enum l4vcpu_irq_state_t
IRQ/Event enable and disable flags.
Enumerator:
L4VCPU_IRQ_STATE_DISABLED
IRQ/Event delivery disabled.
L4VCPU_IRQ_STATE_ENABLED
IRQ/Event delivery enabled.
Definition at line 44 of file vcpu.h.
Function Documentation
l4vcpu_state_t l4vcpu_state (l4_vcpu_state_t const * vcpu) throw () [inline]
Return the state flags of a vCPU.
Parameters:
vcpu Pointer to vCPU area.
Definition at line 225 of file vcpu.h.
Referenced by l4vcpu_irq_disable_save().
void l4vcpu_irq_disable (l4_vcpu_state_t * vcpu) throw () [inline]
Disable a vCPU for event delivery.
Parameters:
vcpu Pointer to vCPU area.
Definition at line 232 of file vcpu.h.
References l4_barrier().
Referenced by l4vcpu_irq_disable_save().
l4vcpu_irq_state_t l4vcpu_irq_disable_save (l4_vcpu_state_t * vcpu) throw () [inline]
Disable a vCPU for event delivery and return previous state.
Parameters:
vcpu Pointer to vCPU area.
Returns:
IRQ state before disabling IRQs.
Definition at line 240 of file vcpu.h.
References l4vcpu_irq_disable(), and l4vcpu_state().
void l4vcpu_irq_enable (l4_vcpu_state_t * vcpu, l4_utcb_t * utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw () [inline]
Enable a vCPU for event delivery.
Parameters:
vcpu Pointer to vCPU area.
utcb Utcb pointer of the calling vCPU.
do_event_work_cb Call-back function that is called in case an event (such as an interrupt) is pending.
setup_ipc Function call-back that is called right before any IPC operation.
< 0 receive and send timeout
Definition at line 263 of file vcpu.h.
References EXPECT_TRUE, l4_barrier(), L4_IPC_BOTH_TIMEOUT_0, and L4_VCPU_SF_IRQ_PENDING.
Referenced by l4vcpu_halt(), and l4vcpu_irq_restore().
void l4vcpu_irq_restore (l4_vcpu_state_t * vcpu, l4vcpu_irq_state_t s, l4_utcb_t * utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw () [inline]
Restore a previously saved IRQ/event state.
Parameters:
vcpu Pointer to vCPU area.
s IRQ state to be restored.
utcb Utcb pointer of the calling vCPU.
do_event_work_cb Call-back function that is called in case an event (such as an interrupt) is pending after enabling.
setup_ipc Function call-back that is called right before any IPC operation.
Definition at line 282 of file vcpu.h.
References L4_VCPU_F_IRQ, and l4vcpu_irq_enable().
void l4vcpu_halt (l4_vcpu_state_t * vcpu, l4_utcb_t * utcb, l4vcpu_event_hndl_t do_event_work_cb, l4vcpu_setup_ipc_t setup_ipc) throw () [inline]
Halt the vCPU (sleep).
Parameters:
vcpu Pointer to vCPU area.
utcb Utcb pointer of the calling vCPU.
do_event_work_cb Call-back function that is called when the vCPU awakes and needs to handle an event/IRQ.
setup_ipc Function call-back that is called right before any IPC operation.
< never timeout
Definition at line 293 of file vcpu.h.
References L4_IPC_NEVER, and l4vcpu_irq_enable().
void l4vcpu_print_state (l4_vcpu_state_t * vcpu, const char * prefix) throw ()
Print the state of a vCPU.
Parameters:
vcpu Pointer to vCPU area.
prefix A prefix for each line printed.
int l4vcpu_is_irq_entry (l4_vcpu_state_t * vcpu) throw () [inline]
Return whether the entry reason was an IRQ/IPC message.
Parameters:
vcpu Pointer to vCPU area.
return 0 if not, !=0 otherwise.
int l4vcpu_is_page_fault_entry (l4_vcpu_state_t * vcpu) throw () [inline]
Return whether the entry reason was a page fault.
Parameters:
vcpu Pointer to vCPU area.
return 0 if not, !=0 otherwise.
L4Re - L4 Runtime Environment