L4Re Reference Manual
L4Re - L4 Runtime Environment
Virtual Registers (UTCBs)
[Object Invocation]
L4 Virtual Registers (UTCB).
Modules
Message Registers (MRs)
Buffer Registers (BRs)
Thread Control Registers (TCRs)
ARM Virtual Registers (UTCB)
amd64 Virtual Registers (UTCB)
x86 Virtual Registers (UTCB)
Files
file utcb.h
UTCB definitions for ARM.
file utcb.h
UTCB definitions for amd64.
file utcb.h
UTCB definitions for X86.
Typedefs
typedef struct l4_utcb_t l4_utcb_t
Opaque type for the UTCB.
Functions
l4_utcb_t * l4_utcb (void) throw ()
Get the UTCB address.
l4_msg_regs_t * l4_utcb_mr (void) throw ()
Get the message-register block of a UTCB.
l4_buf_regs_t * l4_utcb_br (void) throw ()
Get the buffer-register block of a UTCB.
l4_thread_regs_t * l4_utcb_tcr (void) throw ()
Get the thread-control-register block of a UTCB.
Detailed Description
L4 Virtual Registers (UTCB).
Includes:
#include <l4/sys/utcb.h>
The virtual registers are part of the micro-kernel API and are located in the user-level thread control block (UTCB). The UTCB is a data structure defined by the micro kernel and located on kernel-provided memory. Each L4 thread gets a unique UTCB assigned when it is bound to a task (see Thread Control , l4_thread_control_bind() for more information).
The UTCB is arranged in three blocks of virtual registers.
Thread Control Registers (TCRs)
Message Registers (MRs)
Buffer Registers (BRs)
To access the contents of the virtual registers the l4_utcb_mr(), l4_utcb_tcr(), and l4_utcb_br() functions must be used.
Typedef Documentation
typedef struct l4_utcb_t l4_utcb_t
Opaque type for the UTCB.
To access the contents of the virtual registers the l4_utcb_mr(), l4_utcb_tcr(), and l4_utcb_br() functions must be used.
Definition at line 68 of file utcb.h.
Function Documentation
l4_msg_regs_t * l4_utcb_mr (void) throw () [inline]
Get the message-register block of a UTCB.
Returns:
A pointer to the message-register block of u.
Examples:
examples/sys/aliens/main.c, examples/sys/ipc/ipc_example.c, examples/sys/singlestep/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 331 of file utcb.h.
References l4_utcb().
Referenced by L4Re::Util::Vcon_svr< SVR >::dispatch().
l4_buf_regs_t * l4_utcb_br (void) throw () [inline]
Get the buffer-register block of a UTCB.
Returns:
A pointer to the buffer-register block of u.
Definition at line 334 of file utcb.h.
References l4_utcb().
l4_thread_regs_t * l4_utcb_tcr (void) throw () [inline]
Get the thread-control-register block of a UTCB.
Returns:
A pointer to the thread-control-register block of u.
Definition at line 337 of file utcb.h.
References l4_utcb().
L4Re - L4 Runtime Environment