L4Re Reference Manual
L4Re - L4 Runtime Environment
Region map interface
[L4Re C Interface]
Region map C interface.
Enumerations
enum l4re_rm_flags_t {
L4RE_RM_READ_ONLY = 0x01, L4RE_RM_NO_ALIAS = 0x02, L4RE_RM_PAGER = 0x04, L4RE_RM_RESERVED = 0x08,
L4RE_RM_REGION_FLAGS = 0x0f, L4RE_RM_OVERMAP = 0x10, L4RE_RM_SEARCH_ADDR = 0x20, L4RE_RM_IN_AREA = 0x40,
L4RE_RM_EAGER_MAP = 0x80, L4RE_RM_ATTACH_FLAGS = 0xf0
}
Flags for region operations.
Functions
int l4re_rm_reserve_area (l4_addr_t *start, unsigned long size, unsigned flags, unsigned char align) throw ()
int l4re_rm_free_area (l4_addr_t addr) throw ()
int l4re_rm_attach (void **start, unsigned long size, unsigned long flags, l4re_ds_t const mem, l4_addr_t offs, unsigned char align) throw ()
int l4re_rm_detach (void *addr) throw ()
Detach and unmap in current task.
int l4re_rm_detach_ds (void *addr, l4re_ds_t *ds) throw ()
Detach, unmap and return affected dataspace in current task.
int l4re_rm_detach_unmap (l4_addr_t addr, l4_cap_idx_t task) throw ()
Detach and unmap in specified task.
int l4re_rm_detach_ds_unmap (void *addr, l4re_ds_t *ds, l4_cap_idx_t task) throw ()
Detach and unmap in specified task.
int l4re_rm_find (l4_addr_t *addr, unsigned long *size, l4_addr_t *offset, unsigned *flags, l4re_ds_t *m) throw ()
void l4re_rm_show_lists (void) throw ()
Dump region map internal data structures.
int l4re_rm_reserve_area_srv (l4_cap_idx_t rm, l4_addr_t *start, unsigned long size, unsigned flags, unsigned char align) throw ()
int l4re_rm_free_area_srv (l4_cap_idx_t rm, l4_addr_t addr) throw ()
int l4re_rm_attach_srv (l4_cap_idx_t rm, void **start, unsigned long size, unsigned long flags, l4re_ds_t const mem, l4_addr_t offs, unsigned char align) throw ()
int l4re_rm_detach_srv (l4_cap_idx_t rm, l4_addr_t addr, l4re_ds_t *ds, l4_cap_idx_t task) throw ()
int l4re_rm_find_srv (l4_cap_idx_t rm, l4_addr_t *addr, unsigned long *size, l4_addr_t *offset, unsigned *flags, l4re_ds_t *m) throw ()
void l4re_rm_show_lists_srv (l4_cap_idx_t rm) throw ()
Dump region map internal data structures.
Detailed Description
Region map C interface.
Enumeration Type Documentation
enum l4re_rm_flags_t
Flags for region operations.
Enumerator:
L4RE_RM_READ_ONLY
Region is read-only.
L4RE_RM_NO_ALIAS
The region contains exclusive memory that is not mapped anywhere else.
L4RE_RM_PAGER
Region has a pager.
L4RE_RM_RESERVED
Region is reserved (blocked).
L4RE_RM_REGION_FLAGS
Mask of all region flags.
L4RE_RM_OVERMAP
Unmap memory already mapped in the region.
L4RE_RM_SEARCH_ADDR
Search for a suitable address range.
L4RE_RM_IN_AREA
Search only in area, or map into area.
L4RE_RM_EAGER_MAP
Eagerly map the attached data space in.
L4RE_RM_ATTACH_FLAGS
Mask of all attach flags.
Definition at line 40 of file rm.h.
Function Documentation
int l4re_rm_reserve_area (l4_addr_t * start, unsigned long size, unsigned flags, unsigned char align) throw () [inline]
Returns:
0 on success, <0 on error
See also:
L4Re::Rm::reserve_area
This function is using the L4::Env::env()->rm() service.
Definition at line 229 of file rm.h.
References l4re_rm_reserve_area_srv(), and l4re_env_t::rm.
int l4re_rm_free_area (l4_addr_t addr) throw () [inline]
Returns:
0 on success, <0 on error
See also:
L4Re::Rm::free_area
This function is using the L4::Env::env()->rm() service.
Definition at line 237 of file rm.h.
References l4re_rm_free_area_srv(), and l4re_env_t::rm.
int l4re_rm_attach (void ** start, unsigned long size, unsigned long flags, l4re_ds_t const mem, l4_addr_t offs, unsigned char align) throw () [inline]
Parameters:
start Virtual start address
size Size of the data space to attach (in bytes)
flags Flags, see Attach_flags and Region_flags
mem Data space
offs Offset into the data space to use
align Alignment of the virtual region, log2-size, default: a page (L4_PAGESHIFT), Only meaningful if the Search_addr flag is used.
Return values:
start Start of region if Search_addr was used.
Returns:
0 on success, <0 on error
-L4_ENOENT
-L4_EPERM
-L4_EINVAL
-L4_EADDRNOTAVAIL
IPC errors
Makes the whole or parts of a data space visible in the virtual memory of the corresponding task. The corresponding region in the virtual address space is backed with the contents of the dataspace.
Note:
When searching for a free place in the virtual address space, the space between start and the end of the virtual address space is searched.
There is no region object created, instead the region is defined by a virtual address within this range (see find).
Returns:
0 on success, <0 on error
See also:
L4Re::Rm::attach
This function is using the L4::Env::env()->rm() service.
Examples:
examples/libs/l4re/c/ma+rm.c.
Definition at line 243 of file rm.h.
References l4re_rm_attach_srv(), and l4re_env_t::rm.
int l4re_rm_detach (void * addr) throw () [inline]
Detach and unmap in current task.
Parameters:
addr Address of the region to detach.
Returns:
0 on success, <0 on error
Also
See also:
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 253 of file rm.h.
References L4_BASE_TASK_CAP, l4re_rm_detach_srv(), and l4re_env_t::rm.
int l4re_rm_detach_ds (void * addr, l4re_ds_t * ds) throw () [inline]
Detach, unmap and return affected dataspace in current task.
Parameters:
addr Address of the region to detach.
Return values:
ds Returns dataspace that is affected.
Returns:
0 on success, <0 on error
Also
See also:
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Examples:
examples/libs/l4re/c/ma+rm.c.
Definition at line 266 of file rm.h.
References L4_BASE_TASK_CAP, l4re_rm_detach_srv(), and l4re_env_t::rm.
int l4re_rm_detach_unmap (l4_addr_t addr, l4_cap_idx_t task) throw () [inline]
Detach and unmap in specified task.
Parameters:
addr Address of the region to detach.
task Task to unmap pages from, specify L4_INVALID_CAP to not unmap
Returns:
0 on success, <0 on error
Also
See also:
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 260 of file rm.h.
References l4re_rm_detach_srv(), and l4re_env_t::rm.
int l4re_rm_detach_ds_unmap (void * addr, l4re_ds_t * ds, l4_cap_idx_t task) throw () [inline]
Detach and unmap in specified task.
Parameters:
addr Address of the region to detach.
Return values:
ds Returns dataspace that is affected.
Parameters:
task Task to unmap pages from, specify L4_INVALID_CAP to not unmap
Returns:
0 on success, <0 on error
Also
See also:
L4Re::Rm::detach
This function is using the L4::Env::env()->rm() service.
Definition at line 273 of file rm.h.
References l4re_rm_detach_srv(), and l4re_env_t::rm.
int l4re_rm_find (l4_addr_t * addr, unsigned long * size, l4_addr_t * offset, unsigned * flags, l4re_ds_t * m) throw () [inline]
Returns:
0 on success, <0 on error
See also:
L4Re::Rm::find
Definition at line 280 of file rm.h.
References l4re_rm_find_srv(), and l4re_env_t::rm.
void l4re_rm_show_lists (void) throw () [inline]
Dump region map internal data structures.
This function is using the L4::Env::env()->rm() service.
Definition at line 287 of file rm.h.
References l4re_rm_show_lists_srv(), and l4re_env_t::rm.
int l4re_rm_reserve_area_srv (l4_cap_idx_t rm, l4_addr_t * start, unsigned long size, unsigned flags, unsigned char align) throw ()
See also:
L4Re::Rm::reserve_area
Referenced by l4re_rm_reserve_area().
int l4re_rm_free_area_srv (l4_cap_idx_t rm, l4_addr_t addr) throw ()
See also:
L4Re::Rm::free_area
Referenced by l4re_rm_free_area().
int l4re_rm_attach_srv (l4_cap_idx_t rm, void ** start, unsigned long size, unsigned long flags, l4re_ds_t const mem, l4_addr_t offs, unsigned char align) throw ()
See also:
L4Re::Rm::attach
Referenced by l4re_rm_attach().
int l4re_rm_detach_srv (l4_cap_idx_t rm, l4_addr_t addr, l4re_ds_t * ds, l4_cap_idx_t task) throw ()
See also:
L4Re::Rm::detach
Referenced by l4re_rm_detach(), l4re_rm_detach_ds(), l4re_rm_detach_ds_unmap(), and l4re_rm_detach_unmap().
int l4re_rm_find_srv (l4_cap_idx_t rm, l4_addr_t * addr, unsigned long * size, l4_addr_t * offset, unsigned * flags, l4re_ds_t * m) throw ()
See also:
L4Re::Rm::find
Referenced by l4re_rm_find().
L4Re - L4 Runtime Environment