L4Re Reference Manual
L4Re - L4 Runtime Environment
Scheduler
[Kernel Objects]
Scheduler object.
Data Structures
struct l4_sched_cpu_set_t
CPU sets.
struct l4_sched_param_t
Scheduler parameter set.
Typedefs
typedef struct l4_sched_cpu_set_t l4_sched_cpu_set_t
CPU sets.
typedef struct l4_sched_param_t l4_sched_param_t
Scheduler parameter set.
Enumerations
enum L4_scheduler_ops { L4_SCHEDULER_INFO_OP = 0UL, L4_SCHEDULER_RUN_THREAD_OP = 1UL, L4_SCHEDULER_IDLE_TIME_OP = 2UL }
Operations on the Scheduler object.
Functions
l4_sched_cpu_set_t l4_sched_cpu_set (l4_umword_t offset, unsigned char granularity, l4_umword_t map=1) throw ()
l4_msgtag_t l4_scheduler_info (l4_cap_idx_t scheduler, l4_umword_t *cpu_max, l4_sched_cpu_set_t *cpus) throw ()
Get scheduler information.
l4_sched_param_t l4_sched_param (unsigned prio, l4_cpu_time_t quantum=0) throw ()
Construct scheduler parameter.
l4_msgtag_t l4_scheduler_run_thread (l4_cap_idx_t scheduler, l4_cap_idx_t thread, l4_sched_param_t const *sp) throw ()
Run a thread on a Scheduler.
l4_msgtag_t l4_scheduler_idle_time (l4_cap_idx_t scheduler, l4_sched_cpu_set_t const *cpus) throw ()
Query idle time of a CPU, in µs.
int l4_scheduler_is_online (l4_cap_idx_t scheduler, l4_umword_t cpu) throw ()
Query if a CPU is online.
Detailed Description
Scheduler object.
#include <l4/sys/scheduler.h>
Enumeration Type Documentation
enum L4_scheduler_ops
Operations on the Scheduler object.
Enumerator:
L4_SCHEDULER_INFO_OP
Query infos about the scheduler.
L4_SCHEDULER_RUN_THREAD_OP
Run a thread on this scheduler.
L4_SCHEDULER_IDLE_TIME_OP
Query idle time for the scheduler.
Definition at line 185 of file scheduler.h.
Function Documentation
l4_sched_cpu_set_t l4_sched_cpu_set (l4_umword_t offset, unsigned char granularity, l4_umword_t map = 1) throw () [inline]
Parameters:
offset Offset.
granularity Granularitry in log2 notation.
map Bitmap of CPUs, defaults to 1 in C++.
Returns:
CPU set.
Examples:
examples/sys/migrate/thread_migrate.cc.
Definition at line 195 of file scheduler.h.
References l4_sched_cpu_set_t::granularity, l4_sched_cpu_set_t::map, and l4_sched_cpu_set_t::offset.
Referenced by l4_sched_param().
l4_msgtag_t l4_scheduler_info (l4_cap_idx_t scheduler, l4_umword_t * cpu_max, l4_sched_cpu_set_t * cpus) throw () [inline]
Get scheduler information.
Parameters:
scheduler Scheduler object.
Return values:
cpu_max maximum number of CPUs ever available.
Parameters:
cpus cpus.offset is first CPU of interest. cpus.granularity (see l4_sched_cpu_set_t).
Return values:
cpus cpus.map Bitmap of online CPUs.
Returns:
0 on success, <0 error code otherwise.
Definition at line 284 of file scheduler.h.
References l4_utcb().
l4_msgtag_t l4_scheduler_run_thread (l4_cap_idx_t scheduler, l4_cap_idx_t thread, l4_sched_param_t const * sp) throw () [inline]
Run a thread on a Scheduler.
Parameters:
scheduler Scheduler object.
thread Thread to run.
sp Scheduling parameters.
Returns:
0 on success, <0 error code otherwise.
Definition at line 291 of file scheduler.h.
References l4_utcb().
l4_msgtag_t l4_scheduler_idle_time (l4_cap_idx_t scheduler, l4_sched_cpu_set_t const * cpus) throw () [inline]
Query idle time of a CPU, in µs.
Parameters:
scheduler Scheduler object.
cpus Set of CPUs to query.
The consumed time is returned as l4_kernel_clock_t at UTCB message register 0.
Definition at line 298 of file scheduler.h.
References l4_utcb().
int l4_scheduler_is_online (l4_cap_idx_t scheduler, l4_umword_t cpu) throw () [inline]
Query if a CPU is online.
Parameters:
scheduler Scheduler object.
cpu CPU number.
Returns:
true if online, false if not (or any other query error).
Definition at line 304 of file scheduler.h.
References l4_utcb().
L4Re - L4 Runtime Environment