L4Re Reference Manual
L4Re - L4 Runtime Environment
Factory
[Kernel Objects]
A factory is used to create all kinds of kernel objects.
Data Structures
class L4::Factory
C++ L4 Factory, to create all kinds of kernel objects.
Functions
l4_msgtag_t l4_factory_create_task (l4_cap_idx_t factory, l4_cap_idx_t target_cap, l4_fpage_t const utcb_area) throw ()
Create a new task.
l4_msgtag_t l4_factory_create_thread (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw ()
Create a new thread.
l4_msgtag_t l4_factory_create_factory (l4_cap_idx_t factory, l4_cap_idx_t target_cap, unsigned long limit) throw ()
Create a new factory.
l4_msgtag_t l4_factory_create_gate (l4_cap_idx_t factory, l4_cap_idx_t target_cap, l4_cap_idx_t thread_cap, l4_umword_t label) throw ()
Create a new IPC gate.
l4_msgtag_t l4_factory_create_semaphore (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw ()
Create a new semaphore.
l4_msgtag_t l4_factory_create_irq (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw ()
Create a new IRQ.
l4_msgtag_t l4_factory_create_vm (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw ()
Create a new virtual machine.
Detailed Description
A factory is used to create all kinds of kernel objects.
#include <l4/sys/factory.h>
A factory provides the means to create all kinds of kernel objects. The factory is equipped with a limit that limits the amount of kernel memory available for that factory.
Note:
The limit does not give any guarantee for the amount of available kernel memory.
Function Documentation
l4_msgtag_t l4_factory_create_task (l4_cap_idx_t factory, l4_cap_idx_t target_cap, l4_fpage_t const utcb_area) throw () [inline]
Create a new task.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new task.
utcb_area Flexpage that describes the area for the UTCBs of the new task
Note:
The size of the UTCB area specifies indirectly the maximum number of UTCBs available for this task and cannot be changed afterwards.
Returns:
Syscall return tag
See also:
Task
Definition at line 336 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_thread (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw () [inline]
Create a new thread.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new thread.
Returns:
Syscall return tag
See also:
Thread
Examples:
examples/sys/aliens/main.c, examples/sys/singlestep/main.c, examples/sys/start-with-exc/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 343 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_factory (l4_cap_idx_t factory, l4_cap_idx_t target_cap, unsigned long limit) throw () [inline]
Create a new factory.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new factory.
limit Limit for the new factory in bytes
Note:
The limit of the new factory is subtracted from the available amount of the factory used for creation.
Returns:
Syscall return tag
Definition at line 350 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_gate (l4_cap_idx_t factory, l4_cap_idx_t target_cap, l4_cap_idx_t thread_cap, l4_umword_t label) throw () [inline]
Create a new IPC gate.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new IPC gate.
thread_cap Thread to bind the gate to
label Label of the gate
Returns:
Syscall return tag
See also:
IPC-Gate API
Definition at line 358 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_semaphore (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw () [inline]
Create a new semaphore.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new semaphore.
Returns:
Syscall return tag
See also:
l4_sem_api
Definition at line 366 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_irq (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw () [inline]
Create a new IRQ.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new IRQ.
Returns:
Syscall return tag
See also:
IRQs
Examples:
examples/sys/isr/main.c.
Definition at line 373 of file factory.h.
References l4_utcb().
l4_msgtag_t l4_factory_create_vm (l4_cap_idx_t factory, l4_cap_idx_t target_cap) throw () [inline]
Create a new virtual machine.
Parameters:
factory Capability selector for factory to use for creation.
target_cap Capability selector for the root capability of the new VM.
Returns:
Syscall return tag
See also:
Virtual Machines
Definition at line 380 of file factory.h.
References l4_utcb().
L4Re - L4 Runtime Environment