L4Re Reference Manual
L4Re - L4 Runtime Environment
Memory allocator
[L4Re C Interface]
Memory allocator C interface.
Enumerations
enum l4re_ma_flags
Flags for requesting memory at the memory allocator.
Functions
long l4re_ma_alloc (unsigned long size, l4re_ds_t const mem, unsigned long flags) throw ()
Allocate memory.
long l4re_ma_free (l4re_ds_t const mem) throw ()
Free memory.
long l4re_ma_alloc_srv (l4_cap_idx_t srv, unsigned long size, l4re_ds_t const mem, unsigned long flags) throw ()
Allocate memory.
long l4re_ma_free_srv (l4_cap_idx_t srv, l4re_ds_t const mem) throw ()
Free memory.
Detailed Description
Memory allocator C interface.
Enumeration Type Documentation
enum l4re_ma_flags
Flags for requesting memory at the memory allocator.
See also:
L4Re::Mem_alloc::Mem_alloc_flags
Definition at line 42 of file mem_alloc.h.
Function Documentation
long l4re_ma_alloc (unsigned long size, l4re_ds_t const mem, unsigned long flags) throw () [inline]
Allocate memory.
Parameters:
size Size to be requested in bytes (granularity is (super)pages and the size is rounded up to this granularity).
mem Capability slot to put the requested dataspace in
flags Flags, see l4re_ma_flags
Returns:
0 on success, <0 on error
See also:
L4Re::Mem_alloc::alloc
The memory allocator returns a dataspace.
Note:
This function is using the L4Re::Env::env()->mem_alloc() service.
Examples:
examples/libs/l4re/c/ma+rm.c.
Definition at line 123 of file mem_alloc.h.
References l4re_ma_alloc_srv(), and l4re_env_t::mem_alloc.
long l4re_ma_free (l4re_ds_t const mem) throw () [inline]
Free memory.
Parameters:
mem Dataspace to free.
Returns:
0 on success, <0 on error
See also:
L4Re::Mem_alloc::free
Note:
This function is using the L4Re::Env::env()->mem_alloc() service.
Examples:
examples/libs/l4re/c/ma+rm.c.
Definition at line 130 of file mem_alloc.h.
References l4re_ma_free_srv(), and l4re_env_t::mem_alloc.
long l4re_ma_alloc_srv (l4_cap_idx_t srv, unsigned long size, l4re_ds_t const mem, unsigned long flags) throw ()
Allocate memory.
Parameters:
srv Memory allocator service.
size Size to be requested.
mem Capability slot to put the requested dataspace in
flags Flags, see l4re_ma_flags
Returns:
0 on success, <0 on error
See also:
L4Re::Mem_alloc::alloc
The memory allocator returns a dataspace.
Referenced by l4re_ma_alloc().
long l4re_ma_free_srv (l4_cap_idx_t srv, l4re_ds_t const mem) throw ()
Free memory.
Parameters:
srv Memory allocator service.
mem Dataspace to free.
Returns:
0 on success, <0 on error
See also:
L4Re::Mem_alloc::free
Referenced by l4re_ma_free().
L4Re - L4 Runtime Environment