L4Re Reference Manual
L4Re - L4 Runtime Environment
Message Tag
[Object Invocation]
API related to the message tag data type.
Data Structures
struct l4_msgtag_t
Message tag data structure.
Typedefs
typedef struct l4_msgtag_t l4_msgtag_t
Message tag data structure.
Enumerations
enum l4_msgtag_protocol {
L4_PROTO_NONE = 0, L4_PROTO_ALLOW_SYSCALL = 1, L4_PROTO_PF_EXCEPTION = 1, L4_PROTO_IRQ = -1L,
L4_PROTO_PAGE_FAULT = -2L, L4_PROTO_PREEMPTION = -3L, L4_PROTO_SYS_EXCEPTION = -4L, L4_PROTO_EXCEPTION = -5L,
L4_PROTO_SIGMA0 = -6L, L4_PROTO_IO_PAGE_FAULT = -8L, L4_PROTO_KOBJECT = -10L, L4_PROTO_TASK = -11L,
L4_PROTO_THREAD = -12L, L4_PROTO_LOG = -13L, L4_PROTO_SCHEDULER = -14L, L4_PROTO_FACTORY = -15L
}
Message tag for IPC operations.
enum l4_msgtag_flags {
L4_MSGTAG_ERROR, L4_MSGTAG_XCPU, L4_MSGTAG_TRANSFER_FPU, L4_MSGTAG_SCHEDULE,
L4_MSGTAG_PROPAGATE, L4_MSGTAG_FLAGS
}
Flags for message tags.
Functions
l4_msgtag_t l4_msgtag (long label, unsigned words, unsigned items, unsigned flags) throw ()
Create a message tag from the specified values.
long l4_msgtag_label (l4_msgtag_t t) throw ()
Get the protocol of tag.
unsigned l4_msgtag_words (l4_msgtag_t t) throw ()
Get the number of untyped words.
unsigned l4_msgtag_items (l4_msgtag_t t) throw ()
Get the number of typed items.
unsigned l4_msgtag_flags (l4_msgtag_t t) throw ()
Get the flags.
unsigned l4_msgtag_has_error (l4_msgtag_t t) throw ()
Test for error indicator flag.
unsigned l4_msgtag_is_page_fault (l4_msgtag_t t) throw ()
Test for page-fault protocol.
unsigned l4_msgtag_is_preemption (l4_msgtag_t t) throw ()
Test for preemption protocol.
unsigned l4_msgtag_is_sys_exception (l4_msgtag_t t) throw ()
Test for system-exception protocol.
unsigned l4_msgtag_is_exception (l4_msgtag_t t) throw ()
Test for exception protocol.
unsigned l4_msgtag_is_sigma0 (l4_msgtag_t t) throw ()
Test for sigma0 protocol.
unsigned l4_msgtag_is_io_page_fault (l4_msgtag_t t) throw ()
Test for IO-page-fault protocol.
Detailed Description
API related to the message tag data type.
#include <l4/sys/types.h>
Typedef Documentation
typedef struct l4_msgtag_t l4_msgtag_t
Message tag data structure.
#include <l4/sys/types.h>
Describes the details of an IPC operation, in particular which parts of the UTCB have to be transmitted, and also flags to enable real-time and FPU extensions.
The message tag also contains a user-defined label that could be used to specify a protocol ID. Some negative values are reserved for kernel protocols such as page faults and exceptions.
The type must be treated completely opaque.
Enumeration Type Documentation
enum l4_msgtag_protocol
Message tag for IPC operations.
All predefined protocols used by the kernel.
Enumerator:
L4_PROTO_NONE
Default protocol tag to reply to kernel.
L4_PROTO_ALLOW_SYSCALL
Allow an alien the system call.
L4_PROTO_PF_EXCEPTION
Make an exception out of a page fault.
L4_PROTO_IRQ
IRQ message.
L4_PROTO_PAGE_FAULT
Page fault message.
L4_PROTO_PREEMPTION
Preemption message.
L4_PROTO_SYS_EXCEPTION
System exception.
L4_PROTO_EXCEPTION
Exception.
L4_PROTO_SIGMA0
Sigma0 protocol.
L4_PROTO_IO_PAGE_FAULT
I/O page fault message.
L4_PROTO_KOBJECT
Protocol for messages to a a generic kobject.
L4_PROTO_TASK
Protocol for messages to a task object.
L4_PROTO_THREAD
Protocol for messages to a thread object.
L4_PROTO_LOG
Protocol for messages to a log object.
L4_PROTO_SCHEDULER
Protocol for messages to a scheduler object.
L4_PROTO_FACTORY
Protocol for messages to a factory object.
Definition at line 49 of file types.h.
enum l4_msgtag_flags
Flags for message tags.
Enumerator:
L4_MSGTAG_ERROR
Error indicator flag.
L4_MSGTAG_XCPU
Cross-CPU invocation indicator flag.
L4_MSGTAG_TRANSFER_FPU
Enable FPU transfer flag for IPC.
By enabling this flag when sending IPC, the sender indicates that the contents of the FPU shall be transfered to the receiving thread. However, the receiver has to indicate its willingness to receive FPU context in its buffer descriptor register (BDR).
L4_MSGTAG_SCHEDULE
Enable schedule in IPC flag.
Usually IPC operations donate the remaining time slice of a thread to the called thread. Enabling this flag when sending IPC does a real scheduling decision. However, this flag decreases IPC performance.
L4_MSGTAG_PROPAGATE
Enable IPC propagation.
This flag enables IPC propagation, which means an IPC reply-connection from the current caller will be propagated to the new IPC receiver. This makes it possible to propagate an IPC call to a third thread, which may then directly answer to the caller.
L4_MSGTAG_FLAGS
Mask for all flags.
Definition at line 89 of file types.h.
Function Documentation
l4_msgtag_t l4_msgtag (long label, unsigned words, unsigned items, unsigned flags) throw () [inline]
Create a message tag from the specified values.
Message tag functions.
Parameters:
label the user-defined label
words the number of untyped words within the UTCB
items the number of typed items (e.g., flex pages) within the UTCB
flags the IPC flags for realtime and FPU extensions
Returns:
Message tag
Examples:
examples/sys/aliens/main.c, examples/sys/ipc/ipc_example.c, examples/sys/singlestep/main.c, examples/sys/start-with-exc/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 366 of file types.h.
Referenced by fiasco_gdt_get_entry_offset(), fiasco_gdt_set(), fiasco_ldt_set(), L4::Meta::interface(), l4_thread_yield(), L4::Thread::modify_senders(), L4::Meta::num_interfaces(), and L4::Meta::supports().
long l4_msgtag_label (l4_msgtag_t t) throw () [inline]
Get the protocol of tag.
Parameters:
t The tag
Returns:
Label
Examples:
examples/sys/singlestep/main.c, and examples/sys/start-with-exc/main.c.
Definition at line 376 of file types.h.
Referenced by l4_msgtag_is_exception(), l4_msgtag_is_io_page_fault(), l4_msgtag_is_page_fault(), l4_msgtag_is_preemption(), l4_msgtag_is_sigma0(), and l4_msgtag_is_sys_exception().
unsigned l4_msgtag_words (l4_msgtag_t t) throw () [inline]
Get the number of untyped words.
Parameters:
t The tag
Returns:
Number of words
Examples:
examples/sys/utcb-ipc/main.c.
Definition at line 380 of file types.h.
unsigned l4_msgtag_items (l4_msgtag_t t) throw () [inline]
Get the number of typed items.
Parameters:
t The tag
Returns:
Number of items.
Definition at line 384 of file types.h.
unsigned l4_msgtag_flags (l4_msgtag_t t) throw () [inline]
Get the flags.
The flag are defined by l4_msgtag_flags.
Parameters:
t the tag
Returns:
Flags
Definition at line 388 of file types.h.
unsigned l4_msgtag_has_error (l4_msgtag_t t) throw () [inline]
Test for error indicator flag.
Parameters:
t the tag
Returns:
>0 for yes, 0 for no
Return whether the kernel operation caused a communication error, e.g. with IPC. if true: utcb->error is valid, otherwise utcb->error is not valid
Examples:
examples/sys/aliens/main.c, examples/sys/singlestep/main.c, examples/sys/start-with-exc/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 393 of file types.h.
Referenced by l4_ipc_error().
unsigned l4_msgtag_is_page_fault (l4_msgtag_t t) throw () [inline]
Test for page-fault protocol.
Parameters:
t the tag
Returns:
Boolean value
Definition at line 398 of file types.h.
References l4_msgtag_label().
unsigned l4_msgtag_is_preemption (l4_msgtag_t t) throw () [inline]
Test for preemption protocol.
Parameters:
t the tag
Returns:
Boolean value
Definition at line 401 of file types.h.
References l4_msgtag_label().
unsigned l4_msgtag_is_sys_exception (l4_msgtag_t t) throw () [inline]
Test for system-exception protocol.
Parameters:
t the tag
Returns:
Boolean value
Definition at line 404 of file types.h.
References l4_msgtag_label().
unsigned l4_msgtag_is_exception (l4_msgtag_t t) throw () [inline]
Test for exception protocol.
Parameters:
t the tag
Returns:
Boolean value
Examples:
examples/sys/aliens/main.c, examples/sys/singlestep/main.c, and examples/sys/start-with-exc/main.c.
Definition at line 407 of file types.h.
References l4_msgtag_label().
unsigned l4_msgtag_is_sigma0 (l4_msgtag_t t) throw () [inline]
Test for sigma0 protocol.
Parameters:
t the tag
Returns:
Boolean value
Definition at line 410 of file types.h.
References l4_msgtag_label().
unsigned l4_msgtag_is_io_page_fault (l4_msgtag_t t) throw () [inline]
Test for IO-page-fault protocol.
Parameters:
t the tag
Returns:
Boolean value
Definition at line 413 of file types.h.
References l4_msgtag_label().
L4Re - L4 Runtime Environment