L4Re Reference Manual
L4Re - L4 Runtime Environment
Virtual Console
[Kernel Objects]
Virtual console for simple character based input and output.
Data Structures
class L4::Vcon
C++ L4 Vcon.
struct l4_vcon_attr_t
Vcon attribute structure.
Typedefs
typedef struct l4_vcon_attr_t l4_vcon_attr_t
Vcon attribute structure.
Enumerations
enum L4_vcon_write_consts { L4_VCON_WRITE_SIZE = (L4_UTCB_GENERIC_DATA_SIZE - 2) * sizeof(l4_umword_t) }
Constants for l4_vcon_write.
enum L4_vcon_i_flags { L4_VCON_INLCR = 000100, L4_VCON_IGNCR = 000200, L4_VCON_ICRNL = 000400 }
Input flags.
enum L4_vcon_o_flags { L4_VCON_ONLCR = 000004, L4_VCON_OCRNL = 000010, L4_VCON_ONLRET = 000040 }
Output flags.
enum L4_vcon_l_flags { L4_VCON_ECHO = 000010 }
Local flags.
enum L4_vcon_ops { L4_VCON_WRITE_OP = 0UL, L4_VCON_SET_ATTR_OP = 2UL, L4_VCON_GET_ATTR_OP = 3UL }
Operations on the vcon objects.
Functions
l4_msgtag_t l4_vcon_send (l4_cap_idx_t vcon, char const *buf, int size) L4_NOTHROW
Send data to virtual console.
long l4_vcon_write (l4_cap_idx_t vcon, char const *buf, int size) L4_NOTHROW
Write data to virtual console.
int l4_vcon_read (l4_cap_idx_t vcon, char *buf, int size) L4_NOTHROW
Read data from virtual console.
l4_msgtag_t l4_vcon_set_attr (l4_cap_idx_t vcon, l4_vcon_attr_t const *attr) L4_NOTHROW
Set attributes of a Vcon.
l4_msgtag_t l4_vcon_get_attr (l4_cap_idx_t vcon, l4_vcon_attr_t *attr) L4_NOTHROW
Get attributes of a Vcon.
Detailed Description
Virtual console for simple character based input and output.
#include <l4/sys/vcon.h>
Interrupt for read events are provided by the virtual key interrupt.
Enumeration Type Documentation
enum L4_vcon_write_consts
Constants for l4_vcon_write.
Enumerator:
L4_VCON_WRITE_SIZE
Maximum size that can be written with one l4_vcon_write call.
Definition at line 83 of file vcon.h.
enum L4_vcon_i_flags
Input flags.
Enumerator:
L4_VCON_INLCR
Translate NL to CR.
L4_VCON_IGNCR
Ignore CR.
L4_VCON_ICRNL
Translate CR to NL if L4_VCON_IGNCR is not set.
Definition at line 126 of file vcon.h.
enum L4_vcon_o_flags
Output flags.
Enumerator:
L4_VCON_ONLCR
Translate NL to CR-NL.
L4_VCON_OCRNL
Translate CR to NL.
L4_VCON_ONLRET
Do not ouput CR.
Definition at line 137 of file vcon.h.
enum L4_vcon_l_flags
Local flags.
Enumerator:
L4_VCON_ECHO
Echo input.
Definition at line 148 of file vcon.h.
enum L4_vcon_ops
Operations on the vcon objects.
Enumerator:
L4_VCON_WRITE_OP
Write.
L4_VCON_SET_ATTR_OP
Get console attributes.
L4_VCON_GET_ATTR_OP
Set console attributes.
Definition at line 197 of file vcon.h.
Function Documentation
l4_msgtag_t l4_vcon_send (l4_cap_idx_t vcon, char const * buf, int size) [inline]
Send data to virtual console.
Parameters:
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns:
Syscall return tag
Note:
Size must not exceed L4_VCON_WRITE_SIZE.
Definition at line 221 of file vcon.h.
References l4_utcb().
long l4_vcon_write (l4_cap_idx_t vcon, char const * buf, int size) [inline]
Write data to virtual console.
Parameters:
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns:
Number of bytes written to the virtual console.
Definition at line 242 of file vcon.h.
References l4_utcb().
int l4_vcon_read (l4_cap_idx_t vcon, char * buf, int size) [inline]
Read data from virtual console.
Parameters:
vcon Vcon object.
buf Pointer to data buffer.
size Size of buffer in bytes.
Returns:
Negative error code on error, > size if more to read, size bytes are in the buffer, <= size bytes read
Definition at line 279 of file vcon.h.
References l4_utcb().
l4_msgtag_t l4_vcon_set_attr (l4_cap_idx_t vcon, l4_vcon_attr_t const * attr) [inline]
Set attributes of a Vcon.
Parameters:
vcon Vcon object.
attr Attribute structure.
Returns:
Syscall return tag
Definition at line 299 of file vcon.h.
References l4_utcb().
l4_msgtag_t l4_vcon_get_attr (l4_cap_idx_t vcon, l4_vcon_attr_t * attr) [inline]
Get attributes of a Vcon.
Parameters:
vcon Vcon object.
Return values:
attr Attribute structure.
Returns:
Syscall return tag
Definition at line 323 of file vcon.h.
References l4_utcb().
L4Re - L4 Runtime Environment