L4Re Reference Manual
L4Re - L4 Runtime Environment
Log interface
[L4Re C Interface]
Log C interface.
Functions
void l4re_log_print (char const *string) throw ()
Write a null terminated string to the default log.
void l4re_log_printn (char const *string, int len) throw ()
Write a string of a given length to the default log.
void l4re_log_print_srv (const l4_cap_idx_t logcap, char const *string) throw ()
Write a null terminated string to a log.
void l4re_log_printn_srv (const l4_cap_idx_t logcap, char const *string, int len) throw ()
Write a string of a given length to a log.
Detailed Description
Log C interface.
Function Documentation
void l4re_log_print (char const * string) throw () [inline]
Write a null terminated string to the default log.
Parameters:
string Text to print, null terminated.
Returns:
0 for success, <0 on error
See also:
L4Re::Log::print
Definition at line 99 of file log.h.
References l4re_log_print_srv(), and l4re_env_t::log.
void l4re_log_printn (char const * string, int len) throw () [inline]
Write a string of a given length to the default log.
Parameters:
string Text to print, null terminated.
len Length of string in bytes.
Returns:
0 for success, <0 on error
See also:
L4Re::Log::printn
Definition at line 105 of file log.h.
References l4re_log_printn_srv(), and l4re_env_t::log.
void l4re_log_print_srv (const l4_cap_idx_t logcap, char const * string) throw ()
Write a null terminated string to a log.
Parameters:
logcap Log capability (service).
string Text to print, null terminated.
Returns:
0 for success, <0 on error
See also:
L4Re::Log::print
Referenced by l4re_log_print().
void l4re_log_printn_srv (const l4_cap_idx_t logcap, char const * string, int len) throw ()
Write a string of a given length to a log.
Parameters:
logcap Log capability (service).
string Text to print, null terminated.
len Length of string in bytes.
Returns:
0 for success, <0 on error
See also:
L4Re::Log::printn
Referenced by l4re_log_printn().
L4Re - L4 Runtime Environment