L4Re Reference Manual
L4Re - L4 Runtime Environment
Initial Environment
[L4Re C++ Interface]
Environment that is initially provided to an L4 task.
Data Structures
class L4Re::Env
Initial Environment (C++ version).
struct l4re_env_cap_entry_t
Entry in the L4Re environment array for the named inital objects.
struct l4re_env_t
Initial Environment structure (C version).
Typedefs
typedef struct l4re_env_cap_entry_t l4re_env_cap_entry_t
Entry in the L4Re environment array for the named inital objects.
typedef struct l4re_env_t l4re_env_t
Initial Environment structure (C version).
Functions
l4re_env_t * l4re_env (void) throw ()
Get L4Re initial environment (C version).
l4_kernel_info_t * l4re_kip (void) throw ()
Get Kernel Info Page.
l4_cap_idx_t l4re_get_env_cap (char const *name) throw ()
Get the capability selector for the object named name.
l4_cap_idx_t l4re_get_env_cap_e (char const *name, l4re_env_t const *e) throw ()
Get the capability selector for the object named name.
l4re_env_cap_entry_t const * l4re_get_env_cap_l (char const *name, unsigned l, l4re_env_t const *e) throw ()
Get the full l4re_env_cap_entry_t for the object named name.
Detailed Description
Environment that is initially provided to an L4 task.
The initial environment is provided to each L4 task that is started by an L4Re conform loader, such as the Moe root task. The initial environment provides access to a set of initial capabilities and some additional information about the available resources, such as free UTCBs (see Virtual Registers) and available entries in capability table (provided by the micro kernel).
The initial set of capabilities is:
C[parent:L4Re::Parent] --- parent object
C[mem_alloc:L4Re::Mem_alloc] --- initial memory allocator
C[log:L4Re::Log] --- logging facility
C[main_thread:L4::Thread] --- first application thread
C[rm:L4::Rm] --- region manager
C[factory:L4::Factory] --- factory to create kernel objects
C[task:L4::Task] --- the task itself
Additional information is:
First free entry in capability table
The UTCB area (as flex page)
First free UTCB (address in the UTCB area)
See also:
L4Re::Env, l4re_env_t for more information.
Typedef Documentation
typedef struct l4re_env_t l4re_env_t
Initial Environment structure (C version).
See also:
Initial environment
Function Documentation
l4re_env_t * l4re_env (void) throw () [inline]
Get L4Re initial environment (C version).
Returns:
Pointer to L4Re initial environment (C version).
Examples:
examples/sys/aliens/main.c, examples/sys/isr/main.c, examples/sys/singlestep/main.c, examples/sys/start-with-exc/main.c, and examples/sys/utcb-ipc/main.c.
Definition at line 164 of file env.h.
Referenced by l4re_get_env_cap().
l4_kernel_info_t * l4re_kip (void) throw () [inline]
Get Kernel Info Page.
Returns:
Pointer to Kernel Info Page (KIP) structure.
Examples:
examples/sys/aliens/main.c, and examples/sys/ux-vhw/main.c.
Definition at line 168 of file env.h.
l4_cap_idx_t l4re_get_env_cap (char const * name) throw () [inline]
Get the capability selector for the object named name.
Parameters:
name is the name of the object to lookup in the initial objects.
Returns:
A valid capability selector if the object exists or an invalid capability selector if not (l4_is_invalid_cap()).
Examples:
examples/sys/isr/main.c.
Definition at line 205 of file env.h.
References l4re_env(), and l4re_get_env_cap_e().
l4_cap_idx_t l4re_get_env_cap_e (char const * name, l4re_env_t const * e) throw () [inline]
Get the capability selector for the object named name.
Parameters:
name is the name of the object to lookup in the initial objects.
e is the environment structure to use for the operation.
Returns:
A valid capability selector if the object exists or an invalid capability selector if not (l4_is_invalid_cap()).
Definition at line 192 of file env.h.
References l4re_env_cap_entry_t::cap, and l4re_get_env_cap_l().
Referenced by l4re_get_env_cap().
l4re_env_cap_entry_t const * l4re_get_env_cap_l (char const * name, unsigned l, l4re_env_t const * e) throw () [inline]
Get the full l4re_env_cap_entry_t for the object named name.
Parameters:
name is the name of the object to lookup in the initial objects.
l is the length of the name string, thus name might not be zero terminated.
e is the environment structure to use for the operation.
Returns:
A pointer to an l4re_env_cap_entry_t if the object exists or NULL if not.
Definition at line 175 of file env.h.
References l4re_env_cap_entry_t::flags, and l4re_env_cap_entry_t::name.
Referenced by L4Re::Env::get(), and l4re_get_env_cap_e().
L4Re - L4 Runtime Environment