L4Re Reference Manual
L4Re - L4 Runtime Environment
Utility Functions
Modules
CPU related functions
Functions to manipulate the local IDT
Timestamp Counter
Atomic Instructions
Internal functions
Bit Manipulation
ELF binary format
Functions and types related to ELF binaries.
Kernel Interface Page API
Comfortable Command Line Parsing
Priority related functions
Random number support
Machine Restarting Function
Low-Level Thread Functions
IA32 Port I/O API
Bitmap graphics and fonts
This library provides some functions for bitmap handling in frame buffers.
Files
file rand.h
Simple Pseudo-Random Number Generator.
Functions
void l4_sleep_forever (void)) throw ()
Go sleep and never wake up.
long l4util_splitlog2_hdl (l4_addr_t start, l4_addr_t end, long(*handler)(l4_addr_t s, l4_addr_t e, int log2size))
Split a range into log2 base and size aligned chunks.
l4_addr_t l4util_splitlog2_size (l4_addr_t start, l4_addr_t end)
Return log2 base and size aligned length of a range.
l4_timeout_s l4util_micros2l4to (unsigned int mus) throw ()
Calculate l4 timeouts.
Function Documentation
void l4_sleep_forever (void) throw () [inline]
Go sleep and never wake up.
< never timeout
Examples:
examples/libs/libirq/loop.c, and examples/libs/shmc/prodcons.c.
Definition at line 47 of file util.h.
References L4_IPC_NEVER, and l4_ipc_sleep().
long l4util_splitlog2_hdl (l4_addr_t start, l4_addr_t end, long(*)(l4_addr_t s, l4_addr_t e, int log2size) handler) [inline]
Split a range into log2 base and size aligned chunks.
Parameters:
start Start of range
end End of range (inclusive) (e.g. 2-4 is len 3)
handler Handler function that is called with start and end (both inclusive) of the chunk. On success, the handler must return 0, if it returns !=0 the function will immediately return with the return code of the handler.
Returns:
0 on success, != 0 otherwise
Definition at line 53 of file splitlog2.h.
References l4util_splitlog2_size().
l4_addr_t l4util_splitlog2_size (l4_addr_t start, l4_addr_t end) [inline]
Return log2 base and size aligned length of a range.
Parameters:
start Start of range
end End of range (inclusive) (e.g. 2-4 is len 3)
Returns:
length of elements in log2size (length is 1 << log2size)
Definition at line 72 of file splitlog2.h.
References l4util_bsf(), and l4util_bsr().
Referenced by l4util_splitlog2_hdl().
l4_timeout_s l4util_micros2l4to (unsigned int mus) throw ()
Calculate l4 timeouts.
Parameters:
mus time in microseconds. Special cases:
0 - > timeout 0
~0U -> timeout NEVER
Returns:
the corresponding l4_timeout value
L4Re - L4 Runtime Environment